name: anti_mock_gps
description: A Flutter plugin for detecting the emulator device and mock location / fake gps.
version: 1.0.0
homepage: https://github.com/kreazyme/fake_gps_detector
environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: dev.andiksetyawan.fake_gps_detector
        pluginClass: FakeGpsDetectorPlugin
